---
- name: Playbook to create Execution Environment
  hosts: localhost
  gather_facts: false
  vars:
    ee_aap_version: 2.5
    ee_ah_host: galaxy.ansible.com
    ee_registry_dest:  "{{ lookup('env', 'CONTROLLER_HOST') }}/ee-builder-pipeline"
    ee_registry_username:  "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    ee_registry_password:  "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
    ee_list:
      - name: "{{ ee_name }}"
        dependencies:
          ansible_core:
            package_pip: ansible-core
          ansible_runner:
            package_pip: ansible-runner
          system: "{{ system_pkgs }}"
          python: "{{ python_pkgs }}"
          galaxy:
            collections: "{{ galaxy_pkgs }}"
        build_steps:
          prepend_galaxy:
            - ENV ANSIBLE_GALAXY_SERVER_LIST=automation_hub_certified,upstream_galaxy
            - ENV ANSIBLE_GALAXY_SERVER_UPSTREAM_GALAXY_URL=https://galaxy.ansible.com/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_URL=https://console.redhat.com/api/automation-hub/content/validated/
            - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_CERTIFIED_AUTH_URL=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

  roles:
    - infra.ee_utilities.ee_builder
